-- MySQL Script generated by MySQL Workbench
-- Mon Mar 22 19:35:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Registered User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registered User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registered User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seller` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Seller` (
  `seller_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`seller_id`),
  INDEX `seller_to_reg_user_id_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `seller_to_reg_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Registered User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(100) NULL,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(2) NULL,
  `department` VARCHAR(255) NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sells`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sells` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sells` (
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  INDEX `Sells_seller_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `Sells_book_id_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `Sells_seller_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Seller` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Sells_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buyer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buyer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buyer` (
  `buyer_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`buyer_id`),
  CONSTRAINT `buyer_id_FK`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `mydb`.`Registered User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `buyer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `seller_to_transactions_seller_id_idx` (`seller_id` ASC) VISIBLE,
  INDEX `reg_user_to_transactions_buyer_id_idx` (`buyer_id` ASC) VISIBLE,
  CONSTRAINT `seller_to_transactions_seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `mydb`.`Seller` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reg_user_to_transactions_buyer_id`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `mydb`.`Buyer` (`buyer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rating` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_id` INT NOT NULL,
  `origin_uid` INT NOT NULL,
  `target_uid` INT NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `rating_to_reg_user_id_idx` (`target_uid` ASC) VISIBLE,
  CONSTRAINT `rating_to_reg_user_id`
    FOREIGN KEY (`target_uid`)
    REFERENCES `mydb`.`Registered User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Billing Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Billing Info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Billing Info` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Buyer` (`buyer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Payment Type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Payment Type` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `billing_id` INT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`payment_id`, `billing_id`),
  INDEX `billing_to_payment_FK_idx` (`billing_id` ASC) VISIBLE,
  CONSTRAINT `billing_to_payment_FK`
    FOREIGN KEY (`billing_id`)
    REFERENCES `mydb`.`Billing Info` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


